export type StackCategory =
  | 'frontend'
  | 'backend'
  | 'data'
  | 'auth'
  | 'payments'
  | 'telecom'
  | 'connectivity'
  | 'privacy'
  | 'observability'
  | 'operations';

export type StackPriority =
  | 'core'
  | 'primary'
  | 'fallback'
  | 'secondary'
  | 'supporting'
  | 'planned';

export type StackExposure =
  | 'public-client'
  | 'server-only'
  | 'deployment'
  | 'operator-tooling';

export interface StackIntegrationDefinition {
  id: string;
  name: string;
  category: StackCategory;
  priority: StackPriority;
  exposure: StackExposure;
  role: string;
  productSurface: string;
  requiredEnv?: string[];
  optionalEnv?: string[];
  deferredUnlessEnv?: string;
  disabledWhenEnvTrue?: string;
  statusWhenNoEnv?: 'ready' | 'planned';
}

export const CORE_PAYMENT_GATEWAYS = ['paystack', 'paddle', 'nowpayments'] as const;

export const SECONDARY_PAYMENT_GATEWAYS = [
  'flutterwave',
  'squad',
  'korapay',
  'opay',
] as const;

export const STACK_REGISTRY: StackIntegrationDefinition[] = [
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    priority: 'core',
    exposure: 'public-client',
    role: 'Desktop and mobile web application shell',
    productSurface: 'Public site, auth, dashboard, SEO routes',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'react',
    name: 'React',
    category: 'frontend',
    priority: 'core',
    exposure: 'public-client',
    role: 'Web UI runtime',
    productSurface: 'All interactive web surfaces',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    category: 'frontend',
    priority: 'core',
    exposure: 'public-client',
    role: 'Burner Point design system implementation',
    productSurface: 'Web layout, components, brand states',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'frontend',
    priority: 'core',
    exposure: 'public-client',
    role: 'Typed contracts across web, API, and mobile',
    productSurface: 'Compile-time safety',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'operations',
    priority: 'core',
    exposure: 'deployment',
    role: 'Web hosting and edge delivery',
    productSurface: 'Production web deployment',
    requiredEnv: ['VERCEL_ENV'],
    optionalEnv: ['NEXT_PUBLIC_APP_URL'],
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    category: 'backend',
    priority: 'core',
    exposure: 'server-only',
    role: 'Backend API architecture',
    productSurface: 'Auth exchange, numbers, payments, webhooks, provider orchestration',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'railway',
    name: 'Railway',
    category: 'operations',
    priority: 'core',
    exposure: 'deployment',
    role: 'API hosting',
    productSurface: 'Production NestJS deployment',
    requiredEnv: ['RAILWAY_ENVIRONMENT'],
    optionalEnv: ['API_URL', 'APP_URL'],
  },
  {
    id: 'supabase-postgres',
    name: 'Supabase Postgres',
    category: 'data',
    priority: 'core',
    exposure: 'server-only',
    role: 'Primary relational database and managed Postgres runtime',
    productSurface: 'Users, numbers, messages, payments, audit records, and RLS-backed product data',
    requiredEnv: ['DATABASE_URL', 'DIRECT_DATABASE_URL'],
    optionalEnv: ['POOLER_URL', 'SUPABASE_URL', 'DB_SSL'],
  },
  {
    id: 'dbeaver',
    name: 'DBeaver',
    category: 'operations',
    priority: 'supporting',
    exposure: 'operator-tooling',
    role: 'Database inspection client',
    productSurface: 'Manual database operations',
    requiredEnv: ['DATABASE_CLIENT'],
  },
  {
    id: 'supabase-auth',
    name: 'Supabase Auth',
    category: 'auth',
    priority: 'core',
    exposure: 'server-only',
    role: 'Primary authentication and session provider',
    productSurface: 'Sign up, sign in, OAuth, phone auth, password reset, and Supabase session exchange',
    requiredEnv: ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY'],
    optionalEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'EXPO_PUBLIC_SUPABASE_URL', 'EXPO_PUBLIC_SUPABASE_ANON_KEY'],
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'backend',
    priority: 'supporting',
    exposure: 'server-only',
    role: 'Transactional email delivery',
    productSurface: 'Welcome, payment, support, notification emails',
    requiredEnv: ['RESEND_API_KEY'],
    optionalEnv: ['SMTP_HOST', 'SMTP_PASS', 'SMTP_FROM'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'observability',
    priority: 'core',
    exposure: 'server-only',
    role: 'Error monitoring and release diagnostics',
    productSurface: 'Web, API, and Expo monitoring',
    requiredEnv: ['SENTRY_DSN'],
    optionalEnv: ['NEXT_PUBLIC_SENTRY_DSN', 'EXPO_PUBLIC_SENTRY_DSN', 'SENTRY_AUTH_TOKEN'],
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'operations',
    priority: 'core',
    exposure: 'deployment',
    role: 'Source control and CI coordination',
    productSurface: 'Repository, pull requests, release workflow',
    requiredEnv: ['GITHUB_REPOSITORY'],
  },
  {
    id: 'expo',
    name: 'Expo / EAS',
    category: 'frontend',
    priority: 'core',
    exposure: 'deployment',
    role: 'Native mobile app delivery',
    productSurface: 'iOS and Android builds',
    requiredEnv: ['EXPO_PROJECT_ID'],
    optionalEnv: ['EXPO_PUBLIC_API_URL', 'EXPO_PUBLIC_WEB_URL'],
  },
  {
    id: 'revenuecat',
    name: 'RevenueCat',
    category: 'payments',
    priority: 'core',
    exposure: 'server-only',
    role: 'App Store and Google Play subscription entitlement system for BP Messenger, BP Secure Tunnel, and premium mobile plans',
    productSurface: 'Mobile subscription offerings, entitlement sync, webhook reconciliation, and store-managed renewals',
    requiredEnv: ['REVENUECAT_SECRET_API_KEY', 'REVENUECAT_PROJECT_ID'],
    optionalEnv: [
      'REVENUECAT_WEBHOOK_AUTHORIZATION',
      'REVENUECAT_WEBHOOK_SECRET',
      'EXPO_PUBLIC_REVENUECAT_APPLE_API_KEY',
      'EXPO_PUBLIC_REVENUECAT_GOOGLE_API_KEY',
      'NEXT_PUBLIC_REVENUECAT_WEB_API_KEY',
      'REVENUECAT_ENTITLEMENT_BP_MESSENGER',
      'REVENUECAT_ENTITLEMENT_BP_SECURE_TUNNEL',
      'REVENUECAT_ENTITLEMENT_BP_PREMIUM',
      'REVENUECAT_OFFERING_DEFAULT',
      'REVENUECAT_OFFERING_MESSENGER',
      'REVENUECAT_OFFERING_VPN',
    ],
  },
  {
    id: 'apple-developer',
    name: 'Apple Developer Program',
    category: 'operations',
    priority: 'supporting',
    exposure: 'operator-tooling',
    role: 'iOS signing and App Store release',
    productSurface: 'Native iOS distribution',
    requiredEnv: ['APPLE_APP_IDENTIFIER'],
    optionalEnv: ['APPLE_TEAM_ID', 'APP_STORE_CONNECT_KEY_ID'],
  },
  {
    id: 'google-play',
    name: 'Google Play Console',
    category: 'operations',
    priority: 'supporting',
    exposure: 'operator-tooling',
    role: 'Android signing and Play Store release',
    productSurface: 'Native Android distribution',
    requiredEnv: ['GOOGLE_PLAY_PACKAGE_NAME'],
    optionalEnv: ['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'backend',
    priority: 'supporting',
    exposure: 'server-only',
    role: 'AI-assisted message classification with kill switch',
    productSurface: 'Spam/OTP classification and future AI features',
    requiredEnv: ['OPENAI_API_KEY'],
    optionalEnv: ['OPENAI_MODEL', 'AI_KILL_SWITCH'],
    disabledWhenEnvTrue: 'AI_KILL_SWITCH',
  },
  {
    id: 's3-compatible-storage',
    name: 'S3-compatible object storage',
    category: 'data',
    priority: 'planned',
    exposure: 'server-only',
    role: 'Private uploads and sensitive document storage',
    productSurface: 'MMS media, support attachments, future ID uploads',
    requiredEnv: ['AWS_BUCKET', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
    optionalEnv: ['AWS_REGION', 'R2_BUCKET', 'R2_ACCESS_KEY_ID', 'R2_SECRET_ACCESS_KEY', 'R2_PUBLIC_URL'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'redis-queues',
    name: 'Redis-backed background jobs',
    category: 'backend',
    priority: 'core',
    exposure: 'server-only',
    role: 'Retries, OTP velocity windows, webhook dedupe, provider health',
    productSurface: 'Queues, throttles, retry state',
    requiredEnv: ['REDIS_URL'],
    optionalEnv: ['QUEUE_REDIS_URL'],
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'observability',
    priority: 'supporting',
    exposure: 'server-only',
    role: 'Product analytics and event tracking',
    productSurface: 'Activation, billing, verification, abuse funnels',
    requiredEnv: ['POSTHOG_KEY'],
    optionalEnv: ['NEXT_PUBLIC_POSTHOG_KEY', 'POSTHOG_HOST'],
  },
  {
    id: 'audit-logging',
    name: 'Audit and event logging',
    category: 'observability',
    priority: 'core',
    exposure: 'server-only',
    role: 'Security, billing, provider, and developer action traceability',
    productSurface: 'Enterprise and abuse controls',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'abuse-controls',
    name: 'Abuse and fraud controls',
    category: 'backend',
    priority: 'core',
    exposure: 'server-only',
    role: 'Velocity limits, suspicious use detection, gateway protection',
    productSurface: 'Auth, OTP, payments, messaging',
    statusWhenNoEnv: 'ready',
  },
  {
    id: 'paystack',
    name: 'Paystack',
    category: 'payments',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Primary Nigerian/local card and bank payment gateway',
    productSurface: 'Credits, rentals, one-time purchases',
    requiredEnv: ['PAYSTACK_SECRET_KEY'],
    optionalEnv: ['PAYSTACK_WEBHOOK_SECRET', 'PAYSTACK_PUBLIC_KEY', 'PAYMENT_USD_TO_NGN_RATE'],
  },
  {
    id: 'paddle',
    name: 'Paddle',
    category: 'payments',
    priority: 'primary',
    exposure: 'server-only',
    role: 'International cards and merchant-of-record checkout for web billing',
    productSurface: 'Credits, rentals, and web subscription checkout',
    requiredEnv: ['PADDLE_API_KEY', 'PADDLE_WEBHOOK_SECRET'],
    optionalEnv: ['PADDLE_CLIENT_TOKEN', 'PADDLE_PRICE_VERIFICATION', 'PADDLE_PRICE_RENTAL', 'PADDLE_PRICE_SUB_MONTHLY'],
  },
  {
    id: 'nowpayments',
    name: 'NOWPayments',
    category: 'payments',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Crypto checkout',
    productSurface: 'Credits, rentals, one-time purchases',
    requiredEnv: ['NOWPAYMENTS_API_KEY', 'NOWPAYMENTS_IPN_SECRET'],
  },
  {
    id: 'flutterwave',
    name: 'Flutterwave',
    category: 'payments',
    priority: 'secondary',
    exposure: 'server-only',
    role: 'Secondary local payment gateway after core revenue stabilizes',
    productSurface: 'Deferred checkout path',
    requiredEnv: ['FLUTTERWAVE_SECRET_KEY'],
    optionalEnv: ['FLUTTERWAVE_WEBHOOK_SECRET'],
    deferredUnlessEnv: 'SECONDARY_GATEWAYS_ENABLED',
  },
  {
    id: 'squad',
    name: 'Squad by GTCO',
    category: 'payments',
    priority: 'secondary',
    exposure: 'server-only',
    role: 'Secondary local payment gateway after core revenue stabilizes',
    productSurface: 'Deferred checkout path',
    requiredEnv: ['SQUAD_SECRET_KEY'],
    optionalEnv: ['SQUAD_WEBHOOK_SECRET'],
    deferredUnlessEnv: 'SECONDARY_GATEWAYS_ENABLED',
  },
  {
    id: 'korapay',
    name: 'Korapay',
    category: 'payments',
    priority: 'secondary',
    exposure: 'server-only',
    role: 'Secondary local payment gateway after core revenue stabilizes',
    productSurface: 'Deferred checkout path',
    requiredEnv: ['KORAPAY_SECRET_KEY'],
    optionalEnv: ['KORAPAY_WEBHOOK_SECRET'],
    deferredUnlessEnv: 'SECONDARY_GATEWAYS_ENABLED',
  },
  {
    id: 'opay',
    name: 'OPay',
    category: 'payments',
    priority: 'secondary',
    exposure: 'server-only',
    role: 'Secondary wallet/USSD payment gateway after core revenue stabilizes',
    productSurface: 'Deferred checkout path',
    requiredEnv: ['OPAY_MERCHANT_ID', 'OPAY_PRIVATE_KEY'],
    optionalEnv: ['OPAY_WEBHOOK_SECRET'],
    deferredUnlessEnv: 'SECONDARY_GATEWAYS_ENABLED',
  },
  {
    id: 'twilio-conversations',
    name: 'Twilio Conversations / Programmable Messaging / Voice',
    category: 'telecom',
    priority: 'primary',
    exposure: 'server-only',
    role: 'US/Canada SMS, MMS, Voice, Voicemail, WebRTC execution',
    productSurface: 'Conversation inbox',
    requiredEnv: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN'],
    optionalEnv: ['TWILIO_API_KEY', 'TWILIO_API_SECRET', 'TWILIO_DEFAULT_FROM', 'TWILIO_WEBHOOK_SECRET'],
  },
  {
    id: 'telnyx-conversation',
    name: 'Telnyx',
    category: 'telecom',
    priority: 'primary',
    exposure: 'server-only',
    role: 'US/Canada number infrastructure and messaging fallback',
    productSurface: 'Conversation number inventory',
    requiredEnv: ['TELNYX_API_KEY'],
    optionalEnv: ['TELNYX_MESSAGING_PROFILE_ID', 'TELNYX_CONNECTION_ID', 'TELNYX_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'bandwidth-conversation',
    name: 'Bandwidth',
    category: 'telecom',
    priority: 'primary',
    exposure: 'server-only',
    role: 'North America number inventory, messaging, and carrier-grade voice routing',
    productSurface: 'BP Messenger number assignment and fallback call or SMS routing',
    requiredEnv: ['BANDWIDTH_ACCOUNT_ID', 'BANDWIDTH_USERNAME', 'BANDWIDTH_PASSWORD'],
    optionalEnv: ['BANDWIDTH_MESSAGING_APPLICATION_ID', 'BANDWIDTH_VOICE_APPLICATION_ID', 'BANDWIDTH_SITE_ID', 'BANDWIDTH_SIPPEER_ID', 'BANDWIDTH_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'tremil-conversation',
    name: 'Tremil',
    category: 'telecom',
    priority: 'fallback',
    exposure: 'server-only',
    role: 'Economy routing for low-priority conversation traffic',
    productSurface: 'SMS backup routing',
    requiredEnv: ['TREMIL_API_KEY'],
    optionalEnv: ['TREMIL_BASE_URL', 'TREMIL_SECRET', 'TREMIL_WEBHOOK_SECRET'],
  },
  {
    id: 'twilio-verify',
    name: 'Twilio Verify',
    category: 'telecom',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Global SMS and voice verification core',
    productSurface: 'Phone auth and verification purchase flow',
    requiredEnv: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_VERIFY_SERVICE_SID'],
  },
  {
    id: 'telnyx-verify',
    name: 'Telnyx Verify Route',
    category: 'telecom',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Global verification route provider and independent fallback',
    productSurface: 'Global SMS/voice verification fallback and expansion',
    requiredEnv: ['TELNYX_API_KEY'],
    optionalEnv: ['TELNYX_MESSAGING_PROFILE_ID', 'TELNYX_CONNECTION_ID', 'TELNYX_WEBHOOK_SECRET'],
  },
  {
    id: 'bandwidth-verify',
    name: 'Bandwidth Verify Route',
    category: 'telecom',
    priority: 'fallback',
    exposure: 'server-only',
    role: 'Independent North America verification and messaging fallback',
    productSurface: 'BP Verify Hub provider redundancy',
    requiredEnv: ['BANDWIDTH_ACCOUNT_ID', 'BANDWIDTH_USERNAME', 'BANDWIDTH_PASSWORD'],
    optionalEnv: ['BANDWIDTH_MESSAGING_APPLICATION_ID', 'BANDWIDTH_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'tremil-verify',
    name: 'Tremil Verify / SMS',
    category: 'telecom',
    priority: 'fallback',
    exposure: 'server-only',
    role: 'Verification economy route and final fallback',
    productSurface: 'Global verification route chain',
    requiredEnv: ['TREMIL_API_KEY'],
    optionalEnv: ['TREMIL_BASE_URL', 'TREMIL_SECRET', 'TREMIL_WEBHOOK_SECRET'],
  },
  {
    id: 'airalo',
    name: 'Airalo',
    category: 'connectivity',
    priority: 'primary',
    exposure: 'server-only',
    role: 'eSIM purchase, provisioning, and webhooks',
    productSurface: 'eSIM catalog and active eSIM management',
    requiredEnv: ['AIRALO_API_KEY', 'AIRALO_API_SECRET'],
    optionalEnv: ['AIRALO_BASE_URL', 'AIRALO_PLANS_PATH', 'AIRALO_ORDER_PATH', 'AIRALO_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'oxylabs',
    name: 'Oxylabs',
    category: 'connectivity',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Residential/mobile proxy purchase and management',
    productSurface: 'Proxy catalog, credentials, location control',
    requiredEnv: ['OXYLABS_USERNAME', 'OXYLABS_PASSWORD'],
    optionalEnv: ['OXYLABS_BASE_URL', 'OXYLABS_PROXY_ORDER_PATH', 'OXYLABS_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'smartproxy',
    name: 'Smartproxy',
    category: 'connectivity',
    priority: 'fallback',
    exposure: 'server-only',
    role: 'Proxy fulfillment fallback when Oxylabs is unavailable or uneconomical',
    productSurface: 'Proxy catalog backup routing',
    requiredEnv: ['SMARTPROXY_API_KEY'],
    optionalEnv: ['SMARTPROXY_BASE_URL', 'SMARTPROXY_PROXY_ORDER_PATH', 'SMARTPROXY_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
  {
    id: 'wireguard',
    name: 'WireGuard',
    category: 'privacy',
    priority: 'primary',
    exposure: 'server-only',
    role: 'Self-hosted in-platform VPN privacy protection',
    productSurface: 'VPN toggle, server selection, device config lifecycle',
    requiredEnv: ['WIREGUARD_PRIVATE_KEY', 'WIREGUARD_SERVER_ENDPOINT'],
    optionalEnv: ['WIREGUARD_CONTROL_BASE_URL', 'WIREGUARD_CONTROL_API_KEY', 'WIREGUARD_SESSION_PATH', 'WIREGUARD_WEBHOOK_SECRET'],
    statusWhenNoEnv: 'planned',
  },
];
