'use client';
import Link from 'next/link';
import { useState } from 'react';
import { apiRequest, storeTokens } from '../../lib/api';
import { TurnstileWidget } from '../../components/turnstile-widget';

export default function SignUpPage() {
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [turnstileToken, setTurnstileToken] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); try { const tokens = await apiRequest<{ accessToken: string; refreshToken: string; userId: string }>('/auth/register', { method: 'POST', body: JSON.stringify({ email: form.get('email'), phoneNumber: form.get('phoneNumber'), password: form.get('password'), firstName: form.get('firstName'), lastName: form.get('lastName'), acceptTerms: form.get('acceptTerms') === 'on', acceptPrivacy: form.get('acceptPrivacy') === 'on', turnstileToken }) }); storeTokens(tokens); window.location.href = '/onboarding'; } catch (error) { setMessage(error instanceof Error ? error.message : 'Account creation failed. Please try again.'); setBusy(false); } }
  async function googleSignUp() { setBusy(true); setMessage(''); try { const result = await apiRequest<{ url: string }>('/auth/oauth/google', { method: 'POST', body: JSON.stringify({ turnstileToken }) }); window.location.href = result.url; } catch (error) { setMessage(error instanceof Error ? error.message : 'Google sign-up is unavailable.'); setBusy(false); } }
  return <main className="auth-page"><div className="auth-brand"><Link href="/" className="brand"><span className="brand-mark">BP</span><span>Burner Point</span></Link></div><section className="auth-card"><p className="eyebrow">BURNER POINT</p><h1>Create your account.</h1><form onSubmit={submit}><div className="split-fields"><label>First name<input name="firstName" required autoComplete="given-name" /></label><label>Last name<input name="lastName" required autoComplete="family-name" /></label></div><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Phone<input name="phoneNumber" type="tel" required autoComplete="tel" /></label><label>Password<input name="password" type="password" required autoComplete="new-password" minLength={8} /></label><label className="check-label"><input name="acceptTerms" type="checkbox" required /> I agree to the <Link href="/terms-of-service">Terms</Link>.</label><label className="check-label"><input name="acceptPrivacy" type="checkbox" required /> I agree to the <Link href="/privacy-policy">Privacy Policy</Link>.</label><TurnstileWidget onToken={setTurnstileToken} onError={setMessage} /><button className="button button-accent" type="submit" disabled={busy || !turnstileToken}>{busy ? 'Creating...' : 'Continue'} <span>→</span></button></form><button className="google-button" onClick={googleSignUp} disabled={busy || !turnstileToken}>Google</button>{message && <p className="form-message">{message}</p>}<p className="auth-switch">Already have an account? <Link href="/sign-in">Sign in</Link></p></section><footer className="auth-footer"><Link href="/">Return home</Link></footer></main>;
}
